# docker-compose configuration file for user mongodb database
version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: zum
      MONGO_INITDB_ROOT_PASSWORD: zumdev
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ./data/db # local
        target: /data/db # container
